# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stock_info.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'stock_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10stock_info.proto\x12\x0e\x43pyTa.protobuf\"i\n\tStockInfo\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x15\n\x08\x65xchange\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_exchangeJ\x04\x08\x04\x10\x05J\x04\x08\x05\x10\x06R\x0eold_field_name\"\x1d\n\x08TaResult\x12\x11\n\tpriceInfo\x18\x01 \x01(\t\"a\n\tStockList\x12)\n\x06stocks\x18\x01 \x03(\x0b\x32\x19.CpyTa.protobuf.StockInfo\x12)\n\x07results\x18\x02 \x01(\x0b\x32\x18.CpyTa.protobuf.TaResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKINFO']._serialized_start=36
  _globals['_STOCKINFO']._serialized_end=141
  _globals['_TARESULT']._serialized_start=143
  _globals['_TARESULT']._serialized_end=172
  _globals['_STOCKLIST']._serialized_start=174
  _globals['_STOCKLIST']._serialized_end=271
# @@protoc_insertion_point(module_scope)
