# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stock_map.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'stock_map.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import stock_info_pb2 as stock__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstock_map.proto\x12\x0e\x43pyTa.protobuf\x1a\x10stock_info.proto\"\x81\x01\n\x08StockMap\x12.\n\x03map\x18\x01 \x03(\x0b\x32!.CpyTa.protobuf.StockMap.MapEntry\x1a\x45\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.CpyTa.protobuf.StockInfo:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_map_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKMAP_MAPENTRY']._loaded_options = None
  _globals['_STOCKMAP_MAPENTRY']._serialized_options = b'8\001'
  _globals['_STOCKMAP']._serialized_start=54
  _globals['_STOCKMAP']._serialized_end=183
  _globals['_STOCKMAP_MAPENTRY']._serialized_start=114
  _globals['_STOCKMAP_MAPENTRY']._serialized_end=183
# @@protoc_insertion_point(module_scope)
