// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: stock_map.proto
// Protobuf C++ Version: 5.27.0

#include "stock_map.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace SlabStock {
namespace CPyTa {
namespace protobuf {
      template <typename>
PROTOBUF_CONSTEXPR StockMap_MapEntry_DoNotUse::StockMap_MapEntry_DoNotUse(::_pbi::ConstantInitialized) {}
struct StockMap_MapEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StockMap_MapEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StockMap_MapEntry_DoNotUseDefaultTypeInternal() {}
  union {
    StockMap_MapEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StockMap_MapEntry_DoNotUseDefaultTypeInternal _StockMap_MapEntry_DoNotUse_default_instance_;

inline constexpr StockMap::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : map_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR StockMap::StockMap(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct StockMapDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StockMapDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StockMapDefaultTypeInternal() {}
  union {
    StockMap _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StockMapDefaultTypeInternal _StockMap_default_instance_;
}  // namespace protobuf
}  // namespace CPyTa
}  // namespace SlabStock
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_stock_5fmap_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_stock_5fmap_2eproto = nullptr;
const ::uint32_t
    TableStruct_stock_5fmap_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::SlabStock::CPyTa::protobuf::StockMap_MapEntry_DoNotUse, _has_bits_),
        PROTOBUF_FIELD_OFFSET(::SlabStock::CPyTa::protobuf::StockMap_MapEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::SlabStock::CPyTa::protobuf::StockMap_MapEntry_DoNotUse, key_),
        PROTOBUF_FIELD_OFFSET(::SlabStock::CPyTa::protobuf::StockMap_MapEntry_DoNotUse, value_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::SlabStock::CPyTa::protobuf::StockMap, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::SlabStock::CPyTa::protobuf::StockMap, _impl_.map_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::SlabStock::CPyTa::protobuf::StockMap_MapEntry_DoNotUse)},
        {12, -1, -1, sizeof(::SlabStock::CPyTa::protobuf::StockMap)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::SlabStock::CPyTa::protobuf::_StockMap_MapEntry_DoNotUse_default_instance_._instance,
    &::SlabStock::CPyTa::protobuf::_StockMap_default_instance_._instance,
};
const char descriptor_table_protodef_stock_5fmap_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017stock_map.proto\022\030SlabStock.CPyTa.proto"
    "buf\032\020stock_info.proto\"\225\001\n\010StockMap\0228\n\003ma"
    "p\030\001 \003(\0132+.SlabStock.CPyTa.protobuf.Stock"
    "Map.MapEntry\032O\n\010MapEntry\022\013\n\003key\030\001 \001(\t\0222\n"
    "\005value\030\002 \001(\0132#.SlabStock.CPyTa.protobuf."
    "StockInfo:\0028\001b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_stock_5fmap_2eproto_deps[1] =
    {
        &::descriptor_table_stock_5finfo_2eproto,
};
static ::absl::once_flag descriptor_table_stock_5fmap_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_stock_5fmap_2eproto = {
    false,
    false,
    221,
    descriptor_table_protodef_stock_5fmap_2eproto,
    "stock_map.proto",
    &descriptor_table_stock_5fmap_2eproto_once,
    descriptor_table_stock_5fmap_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_stock_5fmap_2eproto::offsets,
    file_level_enum_descriptors_stock_5fmap_2eproto,
    file_level_service_descriptors_stock_5fmap_2eproto,
};
namespace SlabStock {
namespace CPyTa {
namespace protobuf {
// ===================================================================

StockMap_MapEntry_DoNotUse::StockMap_MapEntry_DoNotUse() {}
StockMap_MapEntry_DoNotUse::StockMap_MapEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
const ::google::protobuf::MessageLite::ClassData*
StockMap_MapEntry_DoNotUse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // tc_table
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(StockMap_MapEntry_DoNotUse, _cached_size_),
              false,
          },
          &StockMap_MapEntry_DoNotUse::MergeImpl,
          &StockMap_MapEntry_DoNotUse::kDescriptorMethods,
          &descriptor_table_stock_5fmap_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
// ===================================================================

class StockMap::_Internal {
 public:
};

void StockMap::clear_map() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.map_.Clear();
}
StockMap::StockMap(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SlabStock.CPyTa.protobuf.StockMap)
}
inline PROTOBUF_NDEBUG_INLINE StockMap::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::SlabStock::CPyTa::protobuf::StockMap& from_msg)
      : map_{visibility, arena, from.map_},
        _cached_size_{0} {}

StockMap::StockMap(
    ::google::protobuf::Arena* arena,
    const StockMap& from)
    : ::google::protobuf::Message(arena) {
  StockMap* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:SlabStock.CPyTa.protobuf.StockMap)
}
inline PROTOBUF_NDEBUG_INLINE StockMap::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : map_{visibility, arena},
        _cached_size_{0} {}

inline void StockMap::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
StockMap::~StockMap() {
  // @@protoc_insertion_point(destructor:SlabStock.CPyTa.protobuf.StockMap)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void StockMap::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
StockMap::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(StockMap, _impl_._cached_size_),
              false,
          },
          &StockMap::MergeImpl,
          &StockMap::kDescriptorMethods,
          &descriptor_table_stock_5fmap_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 2, 45, 2> StockMap::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_StockMap_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::SlabStock::CPyTa::protobuf::StockMap>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // map<string, .SlabStock.CPyTa.protobuf.StockInfo> map = 1;
    {PROTOBUF_FIELD_OFFSET(StockMap, _impl_.map_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(StockMap()._impl_.map_)>(
        1, 0, 0, 9,
        11)},
    {::_pbi::TcParser::CreateInArenaStorageCb<::SlabStock::CPyTa::protobuf::StockInfo>},
  }}, {{
    "\41\3\0\0\0\0\0\0"
    "SlabStock.CPyTa.protobuf.StockMap"
    "map"
  }},
};

PROTOBUF_NOINLINE void StockMap::Clear() {
// @@protoc_insertion_point(message_clear_start:SlabStock.CPyTa.protobuf.StockMap)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.map_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* StockMap::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SlabStock.CPyTa.protobuf.StockMap)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // map<string, .SlabStock.CPyTa.protobuf.StockInfo> map = 1;
  if (!_internal_map().empty()) {
    using MapType = ::google::protobuf::Map<std::string, ::SlabStock::CPyTa::protobuf::StockInfo>;
    using WireHelper = _pbi::MapEntryFuncs<std::string, ::SlabStock::CPyTa::protobuf::StockInfo,
                                   _pbi::WireFormatLite::TYPE_STRING,
                                   _pbi::WireFormatLite::TYPE_MESSAGE>;
    const auto& field = _internal_map();

    if (stream->IsSerializationDeterministic() && field.size() > 1) {
      for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "SlabStock.CPyTa.protobuf.StockMap.map");
      }
    } else {
      for (const auto& entry : field) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "SlabStock.CPyTa.protobuf.StockMap.map");
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SlabStock.CPyTa.protobuf.StockMap)
  return target;
}

::size_t StockMap::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SlabStock.CPyTa.protobuf.StockMap)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // map<string, .SlabStock.CPyTa.protobuf.StockInfo> map = 1;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_map_size());
  for (const auto& entry : _internal_map()) {
    total_size += _pbi::MapEntryFuncs<std::string, ::SlabStock::CPyTa::protobuf::StockInfo,
                                   _pbi::WireFormatLite::TYPE_STRING,
                                   _pbi::WireFormatLite::TYPE_MESSAGE>::ByteSizeLong(entry.first, entry.second);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void StockMap::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<StockMap*>(&to_msg);
  auto& from = static_cast<const StockMap&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SlabStock.CPyTa.protobuf.StockMap)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.map_.MergeFrom(from._impl_.map_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StockMap::CopyFrom(const StockMap& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SlabStock.CPyTa.protobuf.StockMap)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void StockMap::InternalSwap(StockMap* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.map_.InternalSwap(&other->_impl_.map_);
}

::google::protobuf::Metadata StockMap::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
}  // namespace CPyTa
}  // namespace SlabStock
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_stock_5fmap_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
