// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mailsettings.proto
// Protobuf C++ Version: 5.27.0

#include "mailsettings.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace cpymail {
namespace protobuf {

inline constexpr RequestResult::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : status_msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        status_code_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RequestResult::RequestResult(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RequestResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestResultDefaultTypeInternal() {}
  union {
    RequestResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestResultDefaultTypeInternal _RequestResult_default_instance_;

inline constexpr Attachment::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        file_path_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Attachment::Attachment(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AttachmentDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AttachmentDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AttachmentDefaultTypeInternal() {}
  union {
    Attachment _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AttachmentDefaultTypeInternal _Attachment_default_instance_;

inline constexpr MailSettings::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : to_addresses_{},
        cc_addresses_{},
        bcc_addresses_{},
        attachments_{},
        subject_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MailSettings::MailSettings(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MailSettingsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MailSettingsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MailSettingsDefaultTypeInternal() {}
  union {
    MailSettings _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MailSettingsDefaultTypeInternal _MailSettings_default_instance_;
}  // namespace protobuf
}  // namespace cpymail
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_mailsettings_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_mailsettings_2eproto = nullptr;
const ::uint32_t
    TableStruct_mailsettings_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::cpymail::protobuf::Attachment, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::cpymail::protobuf::Attachment, _impl_.filename_),
        PROTOBUF_FIELD_OFFSET(::cpymail::protobuf::Attachment, _impl_.file_path_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::cpymail::protobuf::MailSettings, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::cpymail::protobuf::MailSettings, _impl_.to_addresses_),
        PROTOBUF_FIELD_OFFSET(::cpymail::protobuf::MailSettings, _impl_.cc_addresses_),
        PROTOBUF_FIELD_OFFSET(::cpymail::protobuf::MailSettings, _impl_.bcc_addresses_),
        PROTOBUF_FIELD_OFFSET(::cpymail::protobuf::MailSettings, _impl_.subject_),
        PROTOBUF_FIELD_OFFSET(::cpymail::protobuf::MailSettings, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::cpymail::protobuf::MailSettings, _impl_.attachments_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::cpymail::protobuf::RequestResult, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::cpymail::protobuf::RequestResult, _impl_.status_code_),
        PROTOBUF_FIELD_OFFSET(::cpymail::protobuf::RequestResult, _impl_.status_msg_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::cpymail::protobuf::Attachment)},
        {10, -1, -1, sizeof(::cpymail::protobuf::MailSettings)},
        {24, -1, -1, sizeof(::cpymail::protobuf::RequestResult)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::cpymail::protobuf::_Attachment_default_instance_._instance,
    &::cpymail::protobuf::_MailSettings_default_instance_._instance,
    &::cpymail::protobuf::_RequestResult_default_instance_._instance,
};
const char descriptor_table_protodef_mailsettings_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022mailsettings.proto\022\020cpymail.protobuf\"1"
    "\n\nAttachment\022\020\n\010filename\030\001 \001(\t\022\021\n\tfile_p"
    "ath\030\002 \001(\t\"\246\001\n\014MailSettings\022\024\n\014to_address"
    "es\030\001 \003(\t\022\024\n\014cc_addresses\030\002 \003(\t\022\025\n\rbcc_ad"
    "dresses\030\003 \003(\t\022\017\n\007subject\030\004 \001(\t\022\017\n\007messag"
    "e\030\005 \001(\t\0221\n\013attachments\030\006 \003(\0132\034.cpymail.p"
    "rotobuf.Attachment\"8\n\rRequestResult\022\023\n\013s"
    "tatus_code\030\001 \001(\005\022\022\n\nstatus_msg\030\002 \001(\tb\006pr"
    "oto3"
};
static ::absl::once_flag descriptor_table_mailsettings_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_mailsettings_2eproto = {
    false,
    false,
    324,
    descriptor_table_protodef_mailsettings_2eproto,
    "mailsettings.proto",
    &descriptor_table_mailsettings_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_mailsettings_2eproto::offsets,
    file_level_enum_descriptors_mailsettings_2eproto,
    file_level_service_descriptors_mailsettings_2eproto,
};
namespace cpymail {
namespace protobuf {
// ===================================================================

class Attachment::_Internal {
 public:
};

Attachment::Attachment(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cpymail.protobuf.Attachment)
}
inline PROTOBUF_NDEBUG_INLINE Attachment::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::cpymail::protobuf::Attachment& from_msg)
      : filename_(arena, from.filename_),
        file_path_(arena, from.file_path_),
        _cached_size_{0} {}

Attachment::Attachment(
    ::google::protobuf::Arena* arena,
    const Attachment& from)
    : ::google::protobuf::Message(arena) {
  Attachment* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:cpymail.protobuf.Attachment)
}
inline PROTOBUF_NDEBUG_INLINE Attachment::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : filename_(arena),
        file_path_(arena),
        _cached_size_{0} {}

inline void Attachment::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Attachment::~Attachment() {
  // @@protoc_insertion_point(destructor:cpymail.protobuf.Attachment)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Attachment::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.filename_.Destroy();
  _impl_.file_path_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Attachment::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Attachment, _impl_._cached_size_),
              false,
          },
          &Attachment::MergeImpl,
          &Attachment::kDescriptorMethods,
          &descriptor_table_mailsettings_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 53, 2> Attachment::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Attachment_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cpymail::protobuf::Attachment>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string file_path = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Attachment, _impl_.file_path_)}},
    // string filename = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Attachment, _impl_.filename_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string filename = 1;
    {PROTOBUF_FIELD_OFFSET(Attachment, _impl_.filename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string file_path = 2;
    {PROTOBUF_FIELD_OFFSET(Attachment, _impl_.file_path_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\33\10\11\0\0\0\0\0"
    "cpymail.protobuf.Attachment"
    "filename"
    "file_path"
  }},
};

PROTOBUF_NOINLINE void Attachment::Clear() {
// @@protoc_insertion_point(message_clear_start:cpymail.protobuf.Attachment)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.filename_.ClearToEmpty();
  _impl_.file_path_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Attachment::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cpymail.protobuf.Attachment)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string filename = 1;
  if (!this->_internal_filename().empty()) {
    const std::string& _s = this->_internal_filename();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cpymail.protobuf.Attachment.filename");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string file_path = 2;
  if (!this->_internal_file_path().empty()) {
    const std::string& _s = this->_internal_file_path();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cpymail.protobuf.Attachment.file_path");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cpymail.protobuf.Attachment)
  return target;
}

::size_t Attachment::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cpymail.protobuf.Attachment)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string filename = 1;
  if (!this->_internal_filename().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_filename());
  }

  // string file_path = 2;
  if (!this->_internal_file_path().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_file_path());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Attachment::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Attachment*>(&to_msg);
  auto& from = static_cast<const Attachment&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cpymail.protobuf.Attachment)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_filename().empty()) {
    _this->_internal_set_filename(from._internal_filename());
  }
  if (!from._internal_file_path().empty()) {
    _this->_internal_set_file_path(from._internal_file_path());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Attachment::CopyFrom(const Attachment& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cpymail.protobuf.Attachment)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Attachment::InternalSwap(Attachment* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.file_path_, &other->_impl_.file_path_, arena);
}

::google::protobuf::Metadata Attachment::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MailSettings::_Internal {
 public:
};

MailSettings::MailSettings(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cpymail.protobuf.MailSettings)
}
inline PROTOBUF_NDEBUG_INLINE MailSettings::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::cpymail::protobuf::MailSettings& from_msg)
      : to_addresses_{visibility, arena, from.to_addresses_},
        cc_addresses_{visibility, arena, from.cc_addresses_},
        bcc_addresses_{visibility, arena, from.bcc_addresses_},
        attachments_{visibility, arena, from.attachments_},
        subject_(arena, from.subject_),
        message_(arena, from.message_),
        _cached_size_{0} {}

MailSettings::MailSettings(
    ::google::protobuf::Arena* arena,
    const MailSettings& from)
    : ::google::protobuf::Message(arena) {
  MailSettings* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:cpymail.protobuf.MailSettings)
}
inline PROTOBUF_NDEBUG_INLINE MailSettings::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : to_addresses_{visibility, arena},
        cc_addresses_{visibility, arena},
        bcc_addresses_{visibility, arena},
        attachments_{visibility, arena},
        subject_(arena),
        message_(arena),
        _cached_size_{0} {}

inline void MailSettings::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
MailSettings::~MailSettings() {
  // @@protoc_insertion_point(destructor:cpymail.protobuf.MailSettings)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MailSettings::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.subject_.Destroy();
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
MailSettings::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(MailSettings, _impl_._cached_size_),
              false,
          },
          &MailSettings::MergeImpl,
          &MailSettings::kDescriptorMethods,
          &descriptor_table_mailsettings_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 1, 89, 2> MailSettings::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_MailSettings_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cpymail::protobuf::MailSettings>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated string to_addresses = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(MailSettings, _impl_.to_addresses_)}},
    // repeated string cc_addresses = 2;
    {::_pbi::TcParser::FastUR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(MailSettings, _impl_.cc_addresses_)}},
    // repeated string bcc_addresses = 3;
    {::_pbi::TcParser::FastUR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(MailSettings, _impl_.bcc_addresses_)}},
    // string subject = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(MailSettings, _impl_.subject_)}},
    // string message = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(MailSettings, _impl_.message_)}},
    // repeated .cpymail.protobuf.Attachment attachments = 6;
    {::_pbi::TcParser::FastMtR1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(MailSettings, _impl_.attachments_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string to_addresses = 1;
    {PROTOBUF_FIELD_OFFSET(MailSettings, _impl_.to_addresses_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // repeated string cc_addresses = 2;
    {PROTOBUF_FIELD_OFFSET(MailSettings, _impl_.cc_addresses_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // repeated string bcc_addresses = 3;
    {PROTOBUF_FIELD_OFFSET(MailSettings, _impl_.bcc_addresses_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // string subject = 4;
    {PROTOBUF_FIELD_OFFSET(MailSettings, _impl_.subject_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string message = 5;
    {PROTOBUF_FIELD_OFFSET(MailSettings, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .cpymail.protobuf.Attachment attachments = 6;
    {PROTOBUF_FIELD_OFFSET(MailSettings, _impl_.attachments_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::cpymail::protobuf::Attachment>()},
  }}, {{
    "\35\14\14\15\7\7\0\0"
    "cpymail.protobuf.MailSettings"
    "to_addresses"
    "cc_addresses"
    "bcc_addresses"
    "subject"
    "message"
  }},
};

PROTOBUF_NOINLINE void MailSettings::Clear() {
// @@protoc_insertion_point(message_clear_start:cpymail.protobuf.MailSettings)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.to_addresses_.Clear();
  _impl_.cc_addresses_.Clear();
  _impl_.bcc_addresses_.Clear();
  _impl_.attachments_.Clear();
  _impl_.subject_.ClearToEmpty();
  _impl_.message_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* MailSettings::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cpymail.protobuf.MailSettings)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated string to_addresses = 1;
  for (int i = 0, n = this->_internal_to_addresses_size(); i < n; ++i) {
    const auto& s = this->_internal_to_addresses().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cpymail.protobuf.MailSettings.to_addresses");
    target = stream->WriteString(1, s, target);
  }

  // repeated string cc_addresses = 2;
  for (int i = 0, n = this->_internal_cc_addresses_size(); i < n; ++i) {
    const auto& s = this->_internal_cc_addresses().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cpymail.protobuf.MailSettings.cc_addresses");
    target = stream->WriteString(2, s, target);
  }

  // repeated string bcc_addresses = 3;
  for (int i = 0, n = this->_internal_bcc_addresses_size(); i < n; ++i) {
    const auto& s = this->_internal_bcc_addresses().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cpymail.protobuf.MailSettings.bcc_addresses");
    target = stream->WriteString(3, s, target);
  }

  // string subject = 4;
  if (!this->_internal_subject().empty()) {
    const std::string& _s = this->_internal_subject();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cpymail.protobuf.MailSettings.subject");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // string message = 5;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cpymail.protobuf.MailSettings.message");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  // repeated .cpymail.protobuf.Attachment attachments = 6;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_attachments_size());
       i < n; i++) {
    const auto& repfield = this->_internal_attachments().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            6, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cpymail.protobuf.MailSettings)
  return target;
}

::size_t MailSettings::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cpymail.protobuf.MailSettings)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated string to_addresses = 1;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_to_addresses().size());
  for (int i = 0, n = _internal_to_addresses().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_to_addresses().Get(i));
  }
  // repeated string cc_addresses = 2;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_cc_addresses().size());
  for (int i = 0, n = _internal_cc_addresses().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_cc_addresses().Get(i));
  }
  // repeated string bcc_addresses = 3;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_bcc_addresses().size());
  for (int i = 0, n = _internal_bcc_addresses().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_bcc_addresses().Get(i));
  }
  // repeated .cpymail.protobuf.Attachment attachments = 6;
  total_size += 1UL * this->_internal_attachments_size();
  for (const auto& msg : this->_internal_attachments()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // string subject = 4;
  if (!this->_internal_subject().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_subject());
  }

  // string message = 5;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void MailSettings::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MailSettings*>(&to_msg);
  auto& from = static_cast<const MailSettings&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cpymail.protobuf.MailSettings)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_to_addresses()->MergeFrom(from._internal_to_addresses());
  _this->_internal_mutable_cc_addresses()->MergeFrom(from._internal_cc_addresses());
  _this->_internal_mutable_bcc_addresses()->MergeFrom(from._internal_bcc_addresses());
  _this->_internal_mutable_attachments()->MergeFrom(
      from._internal_attachments());
  if (!from._internal_subject().empty()) {
    _this->_internal_set_subject(from._internal_subject());
  }
  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MailSettings::CopyFrom(const MailSettings& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cpymail.protobuf.MailSettings)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MailSettings::InternalSwap(MailSettings* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.to_addresses_.InternalSwap(&other->_impl_.to_addresses_);
  _impl_.cc_addresses_.InternalSwap(&other->_impl_.cc_addresses_);
  _impl_.bcc_addresses_.InternalSwap(&other->_impl_.bcc_addresses_);
  _impl_.attachments_.InternalSwap(&other->_impl_.attachments_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.subject_, &other->_impl_.subject_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
}

::google::protobuf::Metadata MailSettings::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RequestResult::_Internal {
 public:
};

RequestResult::RequestResult(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cpymail.protobuf.RequestResult)
}
inline PROTOBUF_NDEBUG_INLINE RequestResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::cpymail::protobuf::RequestResult& from_msg)
      : status_msg_(arena, from.status_msg_),
        _cached_size_{0} {}

RequestResult::RequestResult(
    ::google::protobuf::Arena* arena,
    const RequestResult& from)
    : ::google::protobuf::Message(arena) {
  RequestResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.status_code_ = from._impl_.status_code_;

  // @@protoc_insertion_point(copy_constructor:cpymail.protobuf.RequestResult)
}
inline PROTOBUF_NDEBUG_INLINE RequestResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : status_msg_(arena),
        _cached_size_{0} {}

inline void RequestResult::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.status_code_ = {};
}
RequestResult::~RequestResult() {
  // @@protoc_insertion_point(destructor:cpymail.protobuf.RequestResult)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RequestResult::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.status_msg_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
RequestResult::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(RequestResult, _impl_._cached_size_),
              false,
          },
          &RequestResult::MergeImpl,
          &RequestResult::kDescriptorMethods,
          &descriptor_table_mailsettings_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 49, 2> RequestResult::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RequestResult_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cpymail::protobuf::RequestResult>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string status_msg = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(RequestResult, _impl_.status_msg_)}},
    // int32 status_code = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RequestResult, _impl_.status_code_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RequestResult, _impl_.status_code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 status_code = 1;
    {PROTOBUF_FIELD_OFFSET(RequestResult, _impl_.status_code_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string status_msg = 2;
    {PROTOBUF_FIELD_OFFSET(RequestResult, _impl_.status_msg_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\36\0\12\0\0\0\0\0"
    "cpymail.protobuf.RequestResult"
    "status_msg"
  }},
};

PROTOBUF_NOINLINE void RequestResult::Clear() {
// @@protoc_insertion_point(message_clear_start:cpymail.protobuf.RequestResult)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.status_msg_.ClearToEmpty();
  _impl_.status_code_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* RequestResult::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:cpymail.protobuf.RequestResult)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 status_code = 1;
  if (this->_internal_status_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_status_code(), target);
  }

  // string status_msg = 2;
  if (!this->_internal_status_msg().empty()) {
    const std::string& _s = this->_internal_status_msg();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cpymail.protobuf.RequestResult.status_msg");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cpymail.protobuf.RequestResult)
  return target;
}

::size_t RequestResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cpymail.protobuf.RequestResult)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string status_msg = 2;
  if (!this->_internal_status_msg().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_status_msg());
  }

  // int32 status_code = 1;
  if (this->_internal_status_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_status_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void RequestResult::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RequestResult*>(&to_msg);
  auto& from = static_cast<const RequestResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cpymail.protobuf.RequestResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_status_msg().empty()) {
    _this->_internal_set_status_msg(from._internal_status_msg());
  }
  if (from._internal_status_code() != 0) {
    _this->_impl_.status_code_ = from._impl_.status_code_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RequestResult::CopyFrom(const RequestResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cpymail.protobuf.RequestResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RequestResult::InternalSwap(RequestResult* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.status_msg_, &other->_impl_.status_msg_, arena);
        swap(_impl_.status_code_, other->_impl_.status_code_);
}

::google::protobuf::Metadata RequestResult::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
}  // namespace cpymail
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_mailsettings_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
