# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mailsettings.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'mailsettings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12mailsettings.proto\x12\x10\x63pymail.protobuf\"1\n\nAttachment\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\tfile_path\x18\x02 \x01(\t\"\xa6\x01\n\x0cMailSettings\x12\x14\n\x0cto_addresses\x18\x01 \x03(\t\x12\x14\n\x0c\x63\x63_addresses\x18\x02 \x03(\t\x12\x15\n\rbcc_addresses\x18\x03 \x03(\t\x12\x0f\n\x07subject\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\x12\x31\n\x0b\x61ttachments\x18\x06 \x03(\x0b\x32\x1c.cpymail.protobuf.Attachment\"8\n\rRequestResult\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x12\n\nstatus_msg\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mailsettings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ATTACHMENT']._serialized_start=40
  _globals['_ATTACHMENT']._serialized_end=89
  _globals['_MAILSETTINGS']._serialized_start=92
  _globals['_MAILSETTINGS']._serialized_end=258
  _globals['_REQUESTRESULT']._serialized_start=260
  _globals['_REQUESTRESULT']._serialized_end=316
# @@protoc_insertion_point(module_scope)
