set(CMAKE_BUILD_TYPE "DEBUG")
set(CMAKE_CXX_COMPILER "/opt/gcc-13.1.0-build/bin/g++")
set(CMAKE_C_COMPILER "/opt/gcc-13.1.0-build/bin/gcc")
set(CMAKE_GENERATOR "Ninja")
set(CMAKE_PREFIX_PATH "/opt/Qt/6.6.0/gcc_64")